--<ScriptOptions statementTerminator=";"/>

CREATE TABLE ing_pro_cpc (
) ENGINE=InnoDB;

CREATE TABLE affect (
) ENGINE=InnoDB;

CREATE TABLE projet (
) ENGINE=InnoDB;

CREATE TABLE ing_cpc (
) ENGINE=InnoDB;

CREATE TABLE ingenieur (
) ENGINE=InnoDB;

CREATE TABLE emploi (
) ENGINE=InnoDB;

CREATE TABLE pro_cpc (
) ENGINE=InnoDB;

CREATE TABLE dept (
) ENGINE=InnoDB;

CREATE TABLE client (
	CODCLI INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	DESIGN VARCHAR(20),
	NOTEL VARCHAR(14),
	ADRESSE VARCHAR(30),
	CODEPOST CHAR(5),
	VILLE VARCHAR(20),
	CORRESP VARCHAR(20),
	LIBSECT VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE type (
) ENGINE=InnoDB;

CREATE TABLE cli_pro (
) ENGINE=InnoDB;

