--<ScriptOptions statementTerminator=";"/>

CREATE TABLE client (
	CODCLI INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	DESIGN VARCHAR(20),
	NOTEL VARCHAR(14),
	ADRESSE VARCHAR(30),
	CODEPOST CHAR(5),
	VILLE VARCHAR(20),
	CORRESP VARCHAR(20),
	LIBSECT VARCHAR(20)
) ENGINE=InnoDB;

